# This file holds general pillars that are shared accross environments
do_not_modify: 'This file is autogenerated by SaltStack. Please DO NOT modify manually!'
egg_repo: http://pypi.python.org/simple
centos_repo: http:///mirror.centos.org/centos/6/os/x86_64
yum_repo: http://localhost:8000/rpms
scm_repo: whyzgeek@github.com
buildout_env: "PATH='/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin' ORACLE_HOME='/usr/lib/oracle/10.2.0.5/client64'"
db_target: /opt/dbs/var
envs:
    test:
        dns_servers:
            - 80.80.80.80
        ntp_server: us.pool.ntp.org`
        cassanda_srvs:
            - 192.168.2.10
        rabbitmq_srvs:
            - 192.168.2.10
        cassandra:
            cluster_name: Test Cluster
            seeds_tokens:
                192.168.2.10: 0
        rabbitmq:
            nodes:
                192.168.2.10:
    qa:
    live:
        dns_servers:
            - 80.80.80.80
        ntp_server: us.pool.ntp.org`
        cassanda_srvs:
            - 192.168.1.10
            - 192.168.1.11
        rabbitmq_srvs:
            - 192.168.1.10
            - 192.168.1.11
        cassandra:
            cluster_name: Live Cluster
            seeds_tokens:
                192.168.1.10: 0
                192.168.1.11: 100
        rabbitmq:
            nodes:
                192.168.1.10:
                192.168.1.11:
pyapps: /opt/share
# You can use similar approach to override
# the needed stuff.
#% if grains['host'] == 'localhost':
#pyapps: /opt/share
#% endif
